### ISSUE TITLE
Inference Speed

### ISSUE THREAD

**Issue by 0-LL-0** [tjuskyzhang/mobilenetv1-ssd-tensorrt#1]
Thank you for sharing the code. My inference speed  is 4ms, and on your 1660 Ti is 1ms. The difference is still a little big. Is this normal?

My configuration environment：windows10 + VS2015 + Nvidia1060 + i5-7500（@3.40GHz）

**Comment by tjuskyzhang** [comment]
I use the FP16 during the inference.  You can check your GPU's compute capability and check if it support FP16. These links may help you:
- https://forums.developer.nvidia.com/t/fp16-support-on-gtx-1060-and-1080/53256
- https://github.com/wang-xinyu/tensorrtx/blob/18fa419ae35bfcbd27248b3eb9329f415f604366/tutorials/check_fp16_int8_support.md
- https://developer.nvidia.com/cuda-gpus#compute
- https://docs.nvidia.com/deeplearning/tensorrt/support-matrix/index.html#hardware-precision-matrix

**Comment by 0-LL-0** [comment]
Oh, I see. Thanks a lot. I'll check my  GPU's compute capability. Is there any loss of accuracy when using fp16 mode?

**Comment by tjuskyzhang** [comment]
Maybe. 
["If you have chosen FP32 or FP16 it should match the results quite closely. If you have chosen INT8 there may be a small gap between the accuracy achieved during training and the inference accuracy. "](https://docs.nvidia.com/deeplearning/tensorrt/developer-guide/index.html)

**Comment by 0-LL-0** [comment]
Wow, got it. Thank u very much.
